<?php 
session_start();
include "lib/corelib.php";
error_reporting(0);
$_SESSION['valor'] = 3; //Activa la opcion del menu actual
include "headers/header.php";
include_once("analyticstracking.php");
?>
  <!-- .................................... $breadcrumb .................................... -->
  <section class="section-breadcrumb section-color-graylighter">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="index.php">Paciente</a><span class="divider">/</span></li>
        <li class="active">Equipo médico</li>
      </ul>
    </div> 
  </section>
  <!-- .................................... $About .................................... -->
  <section class="section-content section-about" id="section-about">
    <div class="container">
      <h2 class="section-title">
        Equipo médico
        <small>¿Necesitas un doctor? Reserva una cita ahora y añade un médico a tu equipo.</small>
        <?php     ?>
      </h2>
      <div class="row">
        <div class="span4">
          <figure>
            <img alt="" src="<?php echo INCLUDES ?>img/gallery/16rct-l.jpg">
          </figure>
        </div>
        <div class="span8">
                   			 	
			<p>¡Hola, <strong><?php echo $_SESSION['nombre']." ".$_SESSION['apellido']?></strong>! Si nunca has reservado una cita en citaDr ya puedes hacerlo, comienza buscando un médico o un especialista de la salud de inmediato.</p>
			<p><a class="btn btn-small btn-primary" href="reservarCita.php">
			  <i class="icon-search"></i>
			  encuentra un doctor
			  </a>
			  
		  </p>
			<!--
begin tag cloud : generated by TagCrowd.com
Feel free to modify as long as you keep this notice.

EMBEDDING INSTRUCTIONS:
1. Customize your cloud's style by editing the CSS where it says CUSTOMIZE below.
2. Insert this code in its entirety into your webpage or blog post.

This code and its rendered image are released under the Creative Commons Attribution-Noncommercial 3.0 Unported License. (http://creativecommons.org/licenses/by-nc/3.0/)

For COMMERCIAL USE LICENSING, visit http://tagcrowd.com/licensing.html
-->
<style type="text/css"><!-- #htmltagcloud{

/******************************************
 * CUSTOMIZE CLOUD CSS BELOW (optional)
 */
	font-size: 100%;
	width: auto;		/* auto or fixed width, e.g. 500px   */
	font-family:'lucida grande','trebuchet ms',arial,helvetica,sans-serif;
	background-color:#fff;
	margin:1em 1em 0 1em;
	border:2px dotted #ddd;
	padding:2em; 
/******************************************
 * END CUSTOMIZE
 */

}#htmltagcloud{line-height:2.4em;word-spacing:normal;letter-spacing:normal;text-transform:none;text-align:justify;text-indent:0}#htmltagcloud a:link{text-decoration:none}#htmltagcloud a:visited{text-decoration:none}#htmltagcloud a:hover{color:white;background-color:#05f}#htmltagcloud a:active{color:white;background-color:#03d}.wrd{padding:0;position:relative}.wrd a{text-decoration:none}.tagcloud0{font-size:1.0em;color:#ACC1F3;z-index:10}.tagcloud0 a{color:#ACC1F3}.tagcloud1{font-size:1.4em;color:#ACC1F3;z-index:9}.tagcloud1 a{color:#ACC1F3}.tagcloud2{font-size:1.8em;color:#86A0DC;z-index:8}.tagcloud2 a{color:#86A0DC}.tagcloud3{font-size:2.2em;color:#86A0DC;z-index:7}.tagcloud3 a{color:#86A0DC}.tagcloud4{font-size:2.6em;color:#607EC5;z-index:6}.tagcloud4 a{color:#607EC5}.tagcloud5{font-size:3.0em;color:#607EC5;z-index:5}.tagcloud5 a{color:#607EC5}.tagcloud6{font-size:3.3em;color:#4C6DB9;z-index:4}.tagcloud6 a{color:#4C6DB9}.tagcloud7{font-size:3.6em;color:#395CAE;z-index:3}.tagcloud7 a{color:#395CAE}.tagcloud8{font-size:3.9em;color:#264CA2;z-index:2}.tagcloud8 a{color:#264CA2}.tagcloud9{font-size:4.2em;color:#133B97;z-index:1}.tagcloud9 a{color:#133B97}.tagcloud10{font-size:4.5em;color:#002A8B;z-index:0}.tagcloud10 a{color:#002A8B}.freq{font-size:10pt !important;color:#bbb}#credit{text-align:center;color:#333;margin-bottom:0.6em;font:0.7em 'lucida grande',trebuchet,'trebuchet ms',verdana,arial,helvetica,sans-serif}#credit a:link{color:#777;text-decoration:none}#credit a:visited{color:#777;text-decoration:none}#credit a:hover{color:white;background-color:#05f}#credit a:active{text-decoration:underline}// -->
</style>

<div id="htmltagcloud"> <span id="0" class="wrd tagcloud0"><a href="#tagcloud">ahora</a></span> <span id="1" class="wrd tagcloud0"><a href="#tagcloud">anade</a></span> <span id="2" class="wrd tagcloud0"><a href="#tagcloud">buscando</a></span> <span id="3" class="wrd tagcloud4"><a href="#tagcloud">cita</a></span> <span id="4" class="wrd tagcloud0"><a href="#tagcloud">citadr</a></span> <span id="5" class="wrd tagcloud0"><a href="#tagcloud">comienza</a></span> <span id="6" class="wrd tagcloud0"><a href="#tagcloud">contacto</a></span> <span id="7" class="wrd tagcloud4"><a href="#tagcloud">de</a></span> <span id="8" class="wrd tagcloud6"><a href="#tagcloud">doctor</a></span> <span id="9" class="wrd tagcloud0"><a href="#tagcloud">en</a></span> <span id="10" class="wrd tagcloud0"><a href="#tagcloud">encuentra</a></span> <span id="11" class="wrd tagcloud6"><a href="#tagcloud">equipo</a></span> <span id="12" class="wrd tagcloud0"><a href="#tagcloud">especialista</a></span> <span id="13" class="wrd tagcloud0"><a href="#tagcloud">hacerlo</a></span> <span id="14" class="wrd tagcloud0"><a href="#tagcloud">hola</a></span> <span id="15" class="wrd tagcloud0"><a href="#tagcloud">inicio</a></span> <span id="16" class="wrd tagcloud0"><a href="#tagcloud">inmediato</a></span> <span id="17" class="wrd tagcloud0"><a href="#tagcloud">la</a></span> <span id="18" class="wrd tagcloud8"><a href="#tagcloud">medico</a></span> <span id="19" class="wrd tagcloud0"><a href="#tagcloud">necesitas</a></span> <span id="20" class="wrd tagcloud0"><a href="#tagcloud">nosotros</a></span> <span id="21" class="wrd tagcloud0"><a href="#tagcloud">nunca</a></span> <span id="22" class="wrd tagcloud4"><a href="#tagcloud">paciente</a></span> <span id="23" class="wrd tagcloud0"><a href="#tagcloud">puedes</a></span> <span id="24" class="wrd tagcloud0"><a href="#tagcloud">registrar</a></span> <span id="25" class="wrd tagcloud0"><a href="#tagcloud">reserva</a></span> <span id="26" class="wrd tagcloud0"><a href="#tagcloud">reservado</a></span> <span id="27" class="wrd tagcloud0"><a href="#tagcloud">salud</a></span> <span id="28" class="wrd tagcloud0"><a href="#tagcloud">si</a></span> <span id="29" class="wrd tagcloud0"><a href="#tagcloud">tu</a></span> <span id="30" class="wrd tagcloud10"><a href="#tagcloud">un</a></span> <span id="31" class="wrd tagcloud4"><a href="#tagcloud">una</a></span> <span id="32" class="wrd tagcloud0"><a href="#tagcloud">ya</a></span> </div><div id="credit">created at <a href="http://tagcrowd.com">TagCrowd.com</a></div>

<!-- end tag cloud : generated by TagCrowd.com : please keep this notice -->

        </div>
      </div>
    </div>
  </section>

  <!-- .................................... $TEAM .................................... -->
  <!--section class="section-content section-team section-color-graylighter" id="section-team">
    <div class="container">
      <h2 class="section-title">
        Equipo
        <small>Quaerat non tempore quos sit esse laudantium facilis cum minima</small>
      </h2>
      <div class="row">
        <div class="span6">
          <div class="row">
            <div class="span2">
              <figure>
                <img alt="" src="<?//php echo INCLUDES ?>img/people/01sqr-s.jpg">
              </figure>
              <p class="btn-group">
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-envelope"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-twitter"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-linkedin"></i>
                </a>
              </p>
            </div>
            <div class="span3">
              <h5>Name Surname</h5>
              <p>Earum tempora unde molestiae maiores architecto minus aperiam harum incidunt ipsa expedita! Quam ad modi labore reprehenderit consequuntur harum assumenda temporibus culpa.</p>
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="row">
            <div class="span2">
              
              <figure>
                <img alt="" src="<?//php echo INCLUDES ?>img/people/02sqr-s.jpg">
              </figure>
              <p class="btn-group">
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-envelope"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-facebook"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-twitter"></i>
                </a>
              </p>
            </div>
            <div class="span3">
              <h5>Name Surname</h5>
              <p>Veniam possimus vel hic minus illo voluptates esse ad dolorum iusto odit libero alias corrupti provident doloribus quam id ut aliquam eius.</p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="span6">
          <div class="row">
            <div class="span2">
              <figure>
                <img alt="" src="<?//php echo INCLUDES ?>img/people/03sqr-s.jpg">
              </figure>
              <p class="btn-group">
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-envelope"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-facebook"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-linkedin"></i>
                </a>
              </p>
            </div>
            <div class="span3">
              <h5>Name Surname</h5>
              <p>Reiciendis deleniti iure repudiandae consectetur totam atque mollitia natus corporis doloremque fuga enim necessitatibus repellat nam molestias eos architecto alias.</p>
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="row">
            <div class="span2">
              <figure>
                <img alt="" src="<?//php echo INCLUDES ?>img/people/04sqr-s.jpg">
              </figure>
              <p class="btn-group">
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-envelope"></i>
                </a>
                <a class="btn btn-squared btn-small" href="#">
                  <i class="icon-linkedin"></i>
                </a>
              </p>
            </div>
            <div class="span3">
              <h5>Name Surname</h5>
              <p>Odio et non rem consectetur ducimus obcaecati hic quas eveniet qui necessitatibus libero quibusdam quod aperiam laboriosam sit a nemo aut porro!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- .................................... $footer .................................... -->
  <?php include "headers/otrofooter.php"; ?>